import type { Metadata } from "next";
import {
  Orelega_One,
  Oxygen,
  Patua_One,
  Righteous,
  Viaoda_Libre,
  Ultra,
} from "next/font/google";

import "./globals.css";
import SmoothScroll from "@/lenis/SmoothScroll";
import TransitionProvider from "@/components/TransitionProvider";
import Nav from "@/components/Nav";
import MenuSection from "@/components/sections/MenuSection";

const righteous = Righteous({
  variable: "--font-righteous",
  subsets: ["latin"],
  weight: "400",
});

const viaLibre = Viaoda_Libre({
  variable: "--font-via-libre",
  subsets: ["latin"],
  weight: "400",
});

const ultra = Ultra({
  variable: "--font-ultra",
  subsets: ["latin"],
  weight: "400",
});

const oxygen = Oxygen({
  variable: "--font-oxygen",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const patuaOne = Patua_One({
  variable: "--font-patua-one",
  subsets: ["latin"],
  weight: "400",
});

const orelegaOne = Orelega_One({
  variable: "--font-orelega-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ultra.variable} ${viaLibre.variable} ${patuaOne.variable} ${oxygen.variable} ${righteous.variable} ${orelegaOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TransitionProvider>
        <Nav />
        <MenuSection />
          <SmoothScroll>{children}</SmoothScroll>
        </TransitionProvider>
      </body>
    </html>
  );
}
